-- CreateTable
CREATE TABLE "PreMarketPrep" (
    "id" SERIAL NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "qqqPrice" DOUBLE PRECISION NOT NULL,
    "multiplier" DOUBLE PRECISION NOT NULL,
    "estimatedMove" DOUBLE PRECISION NOT NULL,
    "nqPrice" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "PreMarketPrep_pkey" PRIMARY KEY ("id")
);
